# Generated by Django 4.0 on 2022-03-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_tag_remove_post_thumbnail_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='construction.jpg', null=True, upload_to='static/images/images'),
        ),
    ]
