# Generated by Django 4.0 on 2022-03-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='construction.jpg', null=True, upload_to='images'),
        ),
    ]
