# Generated by Django 4.0 on 2022-03-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
